---
- name: "Install assets"
  command: "{{ project_php_bin }} bin/console assets:install --symlink  --env={{ project_env_mode }}"
  args:
    chdir: "{{ project_source_path }}"
  become: true
  become_user: "{{ project_web_user }}"

- name: "bazinga:js-translation:dump"
  command: "{{ project_php_bin }} bin/console bazinga:js-translation:dump --merge-domains --env={{ project_env_mode }}"
  args:
    chdir: "{{ project_source_path }}"
  become: true
  become_user: "{{ project_web_user }}"

- name: "fos:js-routing:dump"
  command: "{{ project_php_bin }} bin/console fos:js-routing:dump --env={{ project_env_mode }}"
  args:
    chdir: "{{ project_source_path }}"
  become: true
  become_user: "{{ project_web_user }}"

- name: "Dump assets"
  command: "{{ project_php_bin }} bin/console assetic:dump --forks=6 --env={{ project_env_mode }}"
  args:
    chdir: "{{ project_source_path }}"
  become: true
  become_user: "{{ project_web_user }}"
